name: STAGE3 - Webapp Restart

on:
  workflow_dispatch:

jobs:
  build:
    name: Deployment
    runs-on: stage-runner
    environment: staging
    steps:
    -   name: Deploy Initiated
        if: always()
        id: deploy-initiated
        uses: slackapi/slack-github-action@v1.24.0
        with:
            payload: |
                {
                    "attachments":
                    [
                        {
                            "mrkdwn_in": ["text"],
                            "color": "#36a64f",
                            "pretext": "STAGE3 Webapp Restart Deployment Initiated",
                            "author_name": "${{ github.actor }}",
                            "text": ":rocket: Deploying `${{ github.ref_name }}` to STAGE3"
                        }
                    ]
                }

        env:
            SLACK_WEBHOOK_URL: ${{ secrets.STAGE_SLACK_WEBHOOK }}
            SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

    - name: Deploy
      run: |
        ansible-playbook -vv --private-key /home/ubuntu/.ssh/id_rsa -i deployment-scripts/inventory_aws_ec2.yml deployment-scripts/webapp_deploy.yml -e "env=stage3" -e "host=tag_Name_stage3_replica"
    -   name: Deploy Completed
        if: success()
        id: deploy-success
        uses: slackapi/slack-github-action@v1.24.0
        with:
            payload: |
                {
                    "attachments":
                    [
                        {
                            "mrkdwn_in": ["text"],
                            "color": "#36a64f",
                            "pretext": "STAGE3 Webapp Restart Deployment Succeeded",
                            "author_name": "${{ github.actor }}",
                            "text": ":star-struck: :white_check_mark: Deployment Succeeded `${{ github.ref_name }}` to STAGE3"
                        }
                    ]
                }

        env:
            SLACK_WEBHOOK_URL: ${{ secrets.STAGE_SLACK_WEBHOOK }}
            SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

    -   name: Deploy Failed
        if: failure()
        id: deploy-failed
        uses: slackapi/slack-github-action@v1.24.0
        with:
            payload: |
                {
                    "attachments":
                    [
                        {
                            "mrkdwn_in": ["text"],
                            "color": "#FF0000",
                            "pretext": "STAGE3 Webapp Restart Deployment Failed <!subteam^S05V1EJCFJT|@devsecops-team>",
                            "author_name": "${{ github.actor }}",
                            "text": ":mild-panic-intensifies: :x: Failed Deploying `${{ github.ref_name }}` to STAGE3"
                        }
                    ]
                }

        env:
            SLACK_WEBHOOK_URL: ${{ secrets.STAGE_SLACK_WEBHOOK }}
            SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
  