name: Notify Slack on Success
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, closed, merged]
    
jobs:
  slack_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Build Step
        run: |
          echo "Building the project..."
          # Your build commands go here
          echo "Build succeeded"

      - name: Send success notification to Slack
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"Hey team, the build has succeeded! :sparkles: \nTriggered by: `'"${GITHUB_ACTOR}"'`"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}
