name: Notify Slack on Success

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, closed, merged]

jobs:
  slack_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Send success notification to Slack
        if: success()
        uses: actions/checkout@v3
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: 'GitHub Actions'
          SLACK_ICON_EMOJI: ':white_check_mark:'
        with:
          status: 'success'
          author_name: '${{ github.actor }}'
          title: 'Build Succeeded :tada:'
          message: 'Hey team, the build has succeeded! :sparkles: \nTriggered by: `${{ github.actor }}`'
